yalla-coop/earwig

package-lock.json
package.json
server/app.js
server/database/dbConnection.js

- adds env2 package to app.js and DBConnection
- calls DBConnection in app.js
- please insert your mongo_uris into .env file of root folder

dbConnection added to app.js

---

server/__test__/database/schema/answers.js
server/__test__/database/schema/questions.js
server/database/dummyData/answers.js
server/database/dummyData/questions.js

1. Add the rest of the answers data
2. Add answers schema test file

[chore] Add the rest of the dummy data

---

client/src/App.js
client/src/index.css

remove rem calculation from index.css to be 16px
remove `container` class name from `App`

Fix rem value

---

server/controllers/uploadVerificationImage.js
server/router/index.js

Fix trade authorization to be available for level 1 user
Fix the image to be associated for the logged in user

Fix trade authorization and fix image uploading

---

client/src/Components/Pages/Admin/Organizations/AllOrganizations.js

fix the successful message for activate orgs

---

client/package-lock.json
client/package.json
client/src/App.enzyme.test.js
client/src/App.js

- adds enzyme and adapter to package.json
- creates test for App initial state and handleStateChange method
- exports `initialState` from `App` so that we have a single source of truth for the component and the test
- moves `isMounted` into initial state (is that ok? im not sure)

adds enzyme App test

---

server/controllers/admin/deleteReview.js
server/database/queries/reviews/index.js

delete related answers when deleting a review

---

client/src/App.js
client/src/Components/Common/Navbar/index.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/Search/AutoSuggest.js
client/src/Components/Pages/Search/Search.style.js
client/src/Components/Pages/Search/index.js

Search links profile bug

---

client/src/Components/Pages/Profile/OverallReview.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Review/initialQuestionsValues.js
client/src/Components/Pages/Review/validationSchema.js
server/controllers/review.js

Remove required validation and fix number validation

---

client/src/Components/Pages/Landing/index.js
client/src/Components/Pages/Login/index.js
client/src/Components/Pages/Profile/OverallReview.js
client/src/Components/Pages/Profile/ProfileAnswers/CommentsBox.js
client/src/Components/Pages/Profile/index.js
server/router/index.js

authorize comments to be level3

---

client/src/App.js

this was due to exact being put in the routes component in the App file

Fix admin breaking 

---

client/src/Components/Common/Select.js
client/src/Components/Pages/Profile/OverallReview.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/ProfileAnswers/CommentsBox.js
client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
client/src/Components/Pages/Profile/Reply.js
client/src/Components/Pages/UploadImage/index.js

Fix comment pop up, reply and select issues

---

client/src/Components/Common/Navbar/Menu.js
client/src/Components/Common/Navbar/Menu.style.js
client/src/Components/Common/Navbar/index.js
client/src/Components/Pages/Admin/SideMenu/index.js
client/src/helpers.js

fix redirect to 'Page not found'  during logout

---

client/src/Components/Pages/QuickReview/index.js
client/src/Components/Pages/Review/Question/index.js
client/src/Components/Pages/Review/Review.style.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/ThankYou/ThankYou.style.js
client/src/Components/Pages/ThankYou/index.js

fix bugs: issues  #264 #265 #266

---

client/src/Components/Pages/Review/Question/index.js
server/database/dummyData/questions.js

Add skip logic for company questions

---

client/src/Components/Common/Navbar/Navbar.style.js
client/src/Components/Pages/Landing/index.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/QuickReview/index.js
client/src/Components/Pages/Review/Question/index.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Review/validationSchema.js
client/src/Components/Pages/Signup/index.js

relates  #245  #247  #248  #256  #257

Fix bugs - 2

---

client/src/Components/Common/CommentSection/CommentBox.style.js
client/src/Components/Pages/Admin/Organizations/OrganizationsColumns.js
client/src/Components/Pages/EditProfile/EditProfile.style.js
client/src/Components/Pages/Landing/Landing.style.js
client/src/Components/Pages/Login/Login.style.js
client/src/Components/Pages/Review/Review.style.js
client/src/Components/Pages/Signup/Signup.style.js

Underline links

---

client/src/Components/Common/AntdComponents/ModalComment.js
client/src/Components/Pages/EditProfile/EditProfile.style.js
client/src/Components/Pages/EditProfile/index.js
server/controllers/uploadVerificationImage.js

remove upload verification image option from edit page

---

client/src/App.js
client/src/Components/Common/ScrollToTop.js
client/src/Components/Pages/Admin/Organizations/OrganizationsColumns.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Review/Review.style.js
client/src/Components/Pages/Search/AddProfileSelection.js
client/src/Components/Pages/Search/AutoSuggest.js
client/src/Components/Pages/Search/Search.test.js
client/src/Components/Pages/Search/index.js
server/__test__/api/organizations.addNew.api.js
server/__test__/database/queries/organizations.addNew.js
server/__test__/database/schema/organization.js
server/controllers/organizations.js
server/database/dummyData/index.js
server/database/models/Organization.js
server/database/queries/organizations/index.js

Bug fixes scroll up search

---

server/__test__/api/organizations.addNew.api.js
server/__test__/database/queries/organizations.addNew.js
server/controllers/organizations.js
server/database/models/Organization.js
server/database/queries/organizations/index.js

remove to lowercase from orgs schema

---

client/package-lock.json
client/package.json
package-lock.json
package.json

fix security alert

---

client/package-lock.json
client/package.json
client/src/Components/Pages/Intro/Intro.style.js
client/src/Components/Pages/Intro/index.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/ProfileAnswers/ImageSlider.js
client/src/Components/Pages/Profile/ProfileAnswers/ListAnswer.js
client/src/Components/Pages/Profile/ProfileAnswers/PieAnswer.js
client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
client/src/Components/Pages/Profile/ProfileAnswers/ScatterAnswer.js
client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
client/src/Components/Pages/Profile/ProfileAnswers/YesNoAnswer.js
client/src/Components/Pages/Profile/ReviewSection.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/QuickReview/index.js
client/src/Components/Pages/Review/Review.style.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Review/staticQuestions.js
client/src/Components/Pages/Search/AddProfileReviewStart.js
client/src/Components/Pages/Search/AddProfileSelection.js
client/src/Components/Pages/Search/Search.style.js
client/src/helpers.js
server/helpers/reportMailing.js

Relates #308 #309 #311 #312 #315 #317 #303 #323 #319

Fix bugs pre s2

---

client/src/Components/Common/StaticPages.style.js
client/src/Components/Pages/Search/Search.test.js
client/src/Components/Pages/Search/index.js
server/__test__/api/search.js
server/__test__/database/queries/search.js
server/controllers/getTrades.js
server/controllers/lastReviewed.js
server/database/queries/index.js
server/database/queries/search.js

Fix bugs 2

---

server/controllers/organizations.js
server/helpers/emailAdminTheNewProfile.js
server/middlewares/validation.js
server/router/index.js

Relates #329
to test it: add `PROFILE_EMAIL=<your email>` into `.env` file to receive the email, then create a new organisation profile, you should get an email

Email admin on new profile

---

client/src/Components/Pages/Review/Question/Question.style.js
client/src/Components/Pages/Review/Question/index.js

change the number input to slider

---

package-lock.json
package.json
server/controllers/signup.js
server/helpers/3dParty/mailchimp.js

Setting up mailchimp account
To be able to check this you need to update your .env file (you can find that pinned in slack)

Set up mailchimp

---

client/package-lock.json
client/package.json
client/src/Components/Pages/Admin/Organizations/AllOrganizations.js
client/src/Components/Pages/Admin/Organizations/OrganizationsColumns.js
client/src/Components/Pages/Admin/Reviews/AllReviews.js
client/src/Components/Pages/Admin/Reviews/ReviewsColumns.js
client/src/Components/Pages/Admin/Users/AllUsers.js
client/src/Components/Pages/Admin/Users/UsersColumns.js
server/database/queries/organizations/getOrgsByCategory.js
server/database/queries/reviews/allReviews.js
server/database/queries/user/allUsers.js

Relates #355 #354 #353 #356 #349

Admin sprint 2

---

client/package-lock.json
client/package.json
client/src/Components/Common/ErrorBoundry.js
client/src/index.js
package-lock.json
package.json
server/app.js

Check your email for sentry invitation. throw any error and check the dashboard for the error log. 
relates #327

Set up sentry.io on both client and server

---

client/src/Components/Pages/Profile/ProfileAnswers/BarChartAnswer.js
client/src/Components/Pages/Profile/ProfileAnswers/PieAnswer.js
server/database/dummyData/questions.js

This is related to the old PR https://github.com/yalla-coop/earwig/pull/388
NOTE: You will need to rebuild the database

Change accuracy question in profile to bar chart

---

client/package-lock.json
client/package.json
client/src/Components/Common/HelpfulBubble/HelpfulBubble.style.js
client/src/Components/Common/HelpfulBubble/index.js
client/src/Components/Pages/Profile/OverallReview.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/index.js
client/src/apiUrls.js
server/__test__/api/updateOverallHelpfulPoints.js
server/controllers/updateOverallHelpfulPoints.js
server/database/queries/reviews/index.js
server/database/queries/reviews/updateOverallHelpfullPoints.js
server/database/queries/user/index.js
server/router/index.js

Helpfulness

---

client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
client/src/Components/Pages/Review/Review.style.js
client/src/Components/Pages/Review/index.js

Update review header and add cancel button & change carousel background

---

client/src/App.js
client/src/Components/Pages/UserProfile/UserProfile.style.js
client/src/Components/Pages/UserProfile/index.js
client/src/constants/screenWidths.js
client/src/helpers.js
server/controllers/userInfo.js

inserted helpedPoints into userController and frontend

---

client/src/Components/Common/AntdComponents/DatePicker.js

Date range

---

client/src/Components/Common/Select.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Profile/OverallReview.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Signup/Signup.style.js
client/src/Components/Pages/Signup/index.js
client/src/Components/index.js
server/__test__/api/user.signup.js
server/controllers/profile.js
server/controllers/signup.js
server/controllers/uploadWorksiteImage.js
server/database/models/User.js
server/database/queries/reviews/index.js
server/database/queries/user/index.js
server/middlewares/validation.js
server/router/index.js

Update sign up process with verification

---

server/controllers/feedback.js
server/controllers/thinkingOfDeleting.js

Relates #198
add these into `.env` file with 
```
HELP_EMAIL = help@earwig.work
DELETE_EMAIL = delete@earwig.work
```

update email addresses

---

client/src/Components/Pages/Review/Question/Options/OverallReview.js
client/src/Components/Pages/Review/Question/Options/YesNo.js
client/src/Components/Pages/Review/Question/index.js
client/src/Components/Pages/Review/index.js

when answer some questions (based on wire-frames) with no a textarea will show up to add a comment
relates #359

Replace speech bubble with textarea

---

client/src/Components/Pages/Profile/index.js

bugfix: Parking cost in the profile does not show the right value

---

client/src/Components/Common/Navbar/index.js
client/src/Components/Pages/Profile/OverallReview.js
client/src/Components/Pages/ReportContent/SelectReason.js
client/src/Components/Pages/ReportContent/index.js
client/src/Components/Pages/Signup/index.js
client/src/Components/index.js
server/helpers/emails/reportMailing.js

- fix the issue with the ability to select options during reporting a review.
- Add email template for voice review 
relates #458

Fix select menu in report content page

---

client/src/Components/Pages/EditProfile/EditProfileSection.js

bugfix: animate buttons while submitting + fix add new trade error

---

client/src/Components/Common/Navbar/Menu.js
client/src/Components/Common/Navbar/index.js
client/src/Components/Pages/Profile/OverallReview.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Search/AutoSuggest.js
client/src/Components/Pages/Search/index.js
client/src/Components/Pages/UserProfile/index.js
client/src/Components/Pages/Welcome/index.js
client/src/Components/index.js
client/src/constants/naviagationUrls.js
server/controllers/deleteOrganization.js
server/controllers/profile.js
server/controllers/updateLastViewedOrg.js

redirect to giving review from search page

---

client/src/Components/Common/Button.js
client/src/Components/Pages/Profile/OverallReview.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/Reply.js
client/src/Components/Pages/Profile/Reply.style.js
client/src/Components/Pages/Profile/index.js

Fix reply issues

---

client/src/Components/Common/Select.js
client/src/Components/Pages/EditProfile/EditProfileSection.js

fix search in the Select component

---

client/src/Components/Common/Navbar/index.js
client/src/Components/Pages/Intro/index.js
client/src/Components/Pages/Landing/index.js
client/src/Components/Pages/Login/index.js
client/src/Components/Pages/OrgCheck/index.js
client/src/Components/Pages/Search/Search.style.js
client/src/Components/Pages/Search/index.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/Welcome/Welcome.style.js
client/src/Components/Pages/Welcome/index.js
client/src/Components/index.js
client/src/constants/naviagationUrls.js

Update the signup and after flow for the different type of users

---

client/src/Components/Common/CancelNavbar.js
client/src/Components/Common/Navbar/Menu.style.js
client/src/Components/Common/Navbar/Navbar.style.js
client/src/Components/Common/StaticPages.style.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/ReportContent/SelectReason.js
client/src/Components/Pages/ReportContent/Thanks.js
client/src/Components/Pages/ReportContent/index.js
client/src/Components/Pages/Review/Question/Options/Rate.js
client/src/Components/Pages/Review/Review.style.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Search/Search.style.js
client/src/Components/Pages/Static/CommunityGuidlines.js
client/src/Components/Pages/Static/PrivacyAndTerms.js
client/src/Components/Pages/UserProfile/UserProfile.style.js
client/src/Components/Pages/UserProfile/index.js
client/src/theme.js

Design Fixes 

---

client/src/Components/Pages/Profile/ProfileAnswers/CommentsBox.js
server/helpers/emails/reportMailing.js

Fix: clicking on comment button on org. profile crashes the app

---

client/src/Components/Pages/Profile/ProfileAnswers/ListAnswer.js
client/src/Components/Pages/Profile/ProfileAnswers/PayrollAnswer.js
client/src/Components/Pages/Review/Question/Options/DropDown.js
client/src/Components/Pages/Review/index.js
server/controllers/review.js
server/database/dummyData/questions.js
server/database/queries/review.js

- Build the database before working in this.
- This will be in both agency and payroll profile pages.
relates #452

Payrolls names are clickable + calculate the right average 

---

client/src/App.css
client/src/Components/Common/AntdComponents/DatePicker.js
client/src/Components/Pages/Review/Question/Options/DateRange.js
client/src/Components/Pages/Review/Question/Options/Number.js

1- Fix zoom in on input for iPhone devices.
2. Add color for the `From` , '`To` labels whenever active.
3. Edit the step of the cost slider to be .50
relates #447 #334

Fix date issue + Price input sliders increase by 50p

---

client/src/Components/Common/GiveReview/index.js
client/src/Components/Pages/Search/AddProfileReviewStart.js
client/src/Components/Pages/Search/AddProfileSelection.js
server/helpers/emails/emailAdminTheNewProfile.js

fixbug: create new org. always show already exist and close

---

client/src/Components/Pages/OrgCheck/OrgCheck.style.js
client/src/Components/Pages/OrgCheck/index.js
client/src/Components/Pages/Search/Search.style.js

fixbug: After creating account page loads zoomed and distorted

---

client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Search/AutoSuggest.js
client/src/Components/Pages/Search/index.js
client/src/index.css

- Replace StarRate component (starRateCreator function) with `antd Rate` to solve the issue #307 where the component shows all the start filled on phones
relates #307

Replace the StarRate component with antd Rate component

---

client/src/Components/Pages/Admin/Reviews/AdminReview.style.js
client/src/Components/Pages/Admin/Reviews/AllReviews.js
client/src/Components/Pages/Admin/Reviews/SingleReview.js
client/src/Components/Pages/Profile/OverallReview.js
client/src/Components/Pages/Profile/ProfileAnswers/VoiceReview.js
server/__test__/api/admin/getSingleReview.js
server/controllers/admin/deleteReview.js
server/controllers/admin/getSingleReview.js
server/controllers/admin/updateReviewFields.js
server/database/dbConnection.js
server/database/queries/reviews/getReviewDetails.js
server/database/queries/reviews/index.js
server/router/admin.js

Voice admin + hide empty voice reviews

---

client/public/index.html
client/src/Components/Common/Select.js
client/src/Components/Pages/Admin/Users/UsersColumns.js
client/src/Components/Pages/EditProfile/EditProfileSection.js
client/src/Components/Pages/InviteWorkers/index.js
client/src/Components/Pages/InviteWorkers/inviteWorkers.style.js
client/src/Components/Pages/Search/AutoSuggest.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/ThankYou/ThankYou.style.js
client/src/Components/Pages/ThankYou/index.js
client/src/Components/Pages/UploadImage/index.js
server/controllers/admin/allUsers.js
server/controllers/organizations.js
server/controllers/review.js
server/database/queries/user/allUsers.js
server/router/index.js

relates #571 #570 #579 #574 #572 #568 #569

Bugfixes s2 abdalsamad

---

client/src/Components/Pages/Admin/Organizations/AddEditOrg.js
client/src/Components/Pages/Admin/Reviews/SingleReview.js
client/src/Components/Pages/Admin/Trades/index.js
client/src/Components/Pages/Profile/HeaderSection.js
server/controllers/admin/addOrganizations.js
server/controllers/admin/editOrganization.js
server/controllers/uploadWorksiteImage.js

Relates #587 #590 #608 #609 #585

Fix bugs: Admin

---

.gitignore
client/src/Components/Common/Select.js
client/src/Components/Pages/Review/Question/Options/DropDown.js
client/src/Components/Pages/Review/Question/Question.style.js
client/src/Components/Pages/Review/Question/index.js
client/src/Components/Pages/Review/index.js

Refactor the Add new org. code during giving the review.
relates #602 #592 #578 #515

Fixbugs - add new agency - worksite - payroll during the review process

---

client/src/Components/Pages/Search/AutoSuggest.js

fix the auto focus on autosuggest

---

client/src/Components/Common/Popover/Popover.style.js
client/src/Components/Pages/DeleteProfile/DeleteProfile.style.js
client/src/Components/Pages/DeleteProfile/index.js
client/src/Components/Pages/InviteWorkers/index.js
client/src/Components/Pages/InviteWorkers/inviteWorkers.style.js
client/src/Components/Pages/OrgCheck/OrgCheck.style.js
client/src/Components/Pages/OrgCheck/index.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Profile/OverallReview.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/Reply.js
client/src/Components/Pages/Profile/Reply.style.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/ThankYou/ThankYou.style.js
client/src/Components/Pages/ThankYou/index.js
client/src/Components/Pages/UploadImage/index.js

fix #637 #638 #639 #640 #641 #642 #643 #644 #645 #646 #655

New add features-1

---

client/src/Components/Common/Button.js
client/src/Components/Pages/Admin/Reviews/ReviewsColumns.js
client/src/Components/Pages/Admin/Users/UsersColumns.js
client/src/Components/Pages/EditProfile/EditProfile.style.js
client/src/Components/Pages/EditProfile/EditProfileSection.js
client/src/Components/Pages/EditProfile/index.js
client/src/Components/Pages/Profile/ReviewSection.style.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/Review/Question/Options/YesNo.js
client/src/Components/Pages/UserProfile/index.js
client/src/constants/promoItems.js
server/constants.js
server/controllers/editProfile.js
server/database/dummyData/questions.js

fix  #649 #650 #651 #652 #653 #654  #656

New features 2

---

server/controllers/signup.js
server/controllers/uploadVerificationImage.js
server/helpers/emails/emailAdminTheNewProfile.js
server/helpers/emails/verificationPhotoEmail.js
server/middlewares/uploadFileToServer.js
server/middlewares/uploadToGoogle.js
server/router/index.js

Admin receives and email upon new verification photo or creating new entity profile by a user
fix #647 #648

Admin emails

---

client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/ProfileAnswers/VoiceReview.js
client/src/Components/Pages/Review/Question/Question.style.js

Fix voice recording width going super narrow on heroku

Voice width

---

client/src/Components/Pages/Profile/ProfileAnswers/ImageSlider.js

not related to any issue
just realised that the arrows for the slider are being too large on mobile and take the full width of the worksite images carousel

fix worksite images carousel arrow buttons

---

client/src/Components/Pages/Static/CommunityGuidlines.js
client/src/Components/Pages/Static/PrivacyPolicy.js

Some extra fixes on the other terms pages

Fix typos on community guidelines

---

client/src/Components/index.js

Change the level of access to addNewOrg route to level2 to allow awaiting review users to access it
relates #742

Bug: user can't add new org.

---

client/src/Components/Common/AntdComponents/AntdComponents.style.js
client/src/Components/Common/AntdComponents/DatePicker.js
client/src/Components/Pages/Profile/OverallReview.js

fix reply button color

---

client/src/Components/Pages/Admin/SideMenu/index.js
client/src/Components/Pages/EditProfile/EditProfileSection.js
client/src/Components/Pages/Review/index.js

- Fix a bug in the edit review (due the new changes)
- fixes #761 #764

Bug fixes new

---

client/src/Components/Pages/Signup/Signup.style.js
client/src/Components/Pages/Signup/index.js

refactor sign up page

---

client/src/Components/Common/Navbar/Menu.js
client/src/Components/Pages/Static/CookiesPolicy.js
client/src/Components/Pages/Static/PrivacyPolicy.js
client/src/Components/Pages/Static/TermsOfUse.js

Update legal and menu search link

---

client/src/Components/Common/CancelNavbar.js
client/src/Components/Common/Layout/Layout.style.js
client/src/Components/Common/Layout/Side.js
client/src/Components/Common/Layout/index.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/Reply.js
client/src/Components/Pages/Profile/Reply.style.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/ReportContent/index.js
client/src/Components/Pages/ResetPassword/Content.js
client/src/Components/Pages/ResetPassword/ResetPassword.style.js
client/src/Components/Pages/ResetPassword/index.js
client/src/Components/Pages/Review/Review.style.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Static/PrivacyAndTerms.js

Apply the new layout to the changed pages

---

client/src/Components/Pages/Search/Header/Header.style.js
client/src/Components/Pages/Search/OrganisationsList.js
client/src/Components/Pages/Search/Search.style.js
client/src/Components/Pages/Search/index.js
client/src/helpers/index.js

Improve search performance

---

client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Profile/OverallReview.js
client/src/Components/Pages/Profile/Profile.style.js
server/database/dummyData/questions.js

777 non worker header

---

client/src/helpers/index.js

Fix categories order

---

client/src/Components/Common/AntdComponents/AntdComponents.style.js
client/src/Components/Common/Navbar/Navbar.style.js
client/src/Components/Pages/PreReview/PreReview.style.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/Reply.js
client/src/Components/Pages/Profile/ReviewSection.js
client/src/Components/Pages/Review/Question/Options/Number.js
client/src/Components/Pages/Review/Question/Options/Rate.js
client/src/Components/Pages/Review/Question/Options/YesNo.js
client/src/Components/Pages/Review/Question/Question.style.js
client/src/Components/Pages/Review/Question/index.js
client/src/Components/Pages/Review/Review.style.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Review/staticQuestions.js
client/src/Components/Pages/Search/Header/Header.style.js
client/src/Components/Pages/Search/Header/index.js
client/src/Components/Pages/Search/Search.style.js
client/src/Components/Pages/UserProfile/UserReviews.js
client/src/Components/Pages/Welcome/Welcome.style.js
client/src/Components/Pages/Welcome/index.js
client/src/Components/index.js

Relates #765 
this PR solve some of the notes in #765 issue but not all

765 design notes (Part 1)

---

client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
client/src/Components/Pages/Profile/index.js
server/database/dummyData/questions.js

Render car price > #775

---

client/public/index.html
client/src/Components/Pages/Review/Review.style.js

784 samsung

---

client/src/Components/Common/Button.js
client/src/Components/Pages/DeleteProfile/index.js
client/src/Components/Pages/EditProfile/EditProfileSection.js
client/src/Components/Pages/EditProfile/index.js
client/src/Components/Pages/Signup/Signup.style.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/UploadImage/UploadImage.style.js
client/src/Components/Pages/UploadImage/index.js
client/src/Components/Pages/UserProfile/UserProfile.style.js
client/src/Components/Pages/UserProfile/index.js

783 copy updates

---

client/package-lock.json
client/src/Components/Pages/Review/Question/Options/YesNo.js
client/src/Components/Pages/Review/index.js
package-lock.json

This can be checked in any agency review at this question "Were you paid via a payroll company?"

Delete old irrelevant old answers based on the questions flow.

---

client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Review/Review.style.js
server/database/queries/reviews/index.js

- Limit the reviews in the profile page to 3 at max for level 1 user (not logged in) Relates #790 
- fix the header z-index to be at the top of the other layers in the profile page
- fix header width in review page

790 level 1 limitation

---

client/src/Components/Pages/Static/CookiesPolicy.js

update cookies policy page

---

client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Review/Review.style.js
client/src/Components/Pages/Search/AutoSuggest.js
client/src/Components/Pages/Search/Search.style.js
server/database/queries/reviews/index.js

Relates #794 
this PR pulled from #797 so should be merged after 797

search scrolling layers 

---

client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/Review/Question/Options/Rate.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Review/staticQuestions.js
server/constants.js
server/database/dummyData/answers.js
server/database/dummyData/questions.js

relates #791 
All done except the tool-tip bit which I agree on moving to another issue as @thejoefriel  suggested

Updates to reviewing pages

---

client/src/Components/Pages/Profile/ProfileAnswers/ListAnswer.js
client/src/Components/Pages/Profile/ProfileAnswers/PieAnswer.js
client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
client/src/Components/Pages/Profile/ProfileAnswers/YesNoAnswer.js
client/src/Components/Pages/Review/Question/Options/YesNo.js
client/src/Components/Pages/Review/Question/index.js
server/controllers/admin/getAllReviewsCSV.js

Remove question-specific commenting altogether

---

client/src/Components/Common/ToolTip.js
client/src/Components/Pages/Review/Question/index.js
client/src/Components/Pages/Review/staticQuestions.js

Fix the tooltip icon size

---

client/src/helpers/index.js
server/controllers/search.js

Update the sorting order for the orgs list to account for special charachters

---

client/src/Components/Pages/Profile/HeaderSection.js

fix navbar bug

---

client/src/Components/Pages/Profile/DetailedSection/DetailedAnswers.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/Profile/utils.js
server/constants.js
server/database/dummyData/questions.js

Fix worksite render and give profile crashing 

---

client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Search/Search.style.js

829 stars width

---

client/src/Components/Pages/Review/index.js

make cancel review link redirect to profile page

---

client/src/Components/Common/Navbar/index.js

add search icon to the navbar

---

client/src/Components/Pages/Search/Header/index.js

shrink input height by default

---

client/src/Components/Common/CancelNavbar.js
client/src/Components/Common/Select.js
client/src/Components/Pages/EditProfile/EditProfileSection.js
client/src/Components/Pages/ReportContent/SelectReason.js
client/src/Components/Pages/Review/Question/Options/DropDown.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/UploadImage/index.js

841 select components spaces

---

client/src/Components/Common/Navbar/Menu.style.js
client/src/Components/Common/Navbar/Navbar.style.js
client/src/Components/Common/Navbar/index.js

fix menu icon width

---

client/src/Components/Pages/Profile/ProfileAnswers/ImageSlider.js
client/src/Components/Pages/Review/Question/UploadPhoto.js
package-lock.json
package.json
server/controllers/getWorksiteImgs.js
server/controllers/uploadVoiceRecording.js
server/middlewares/deleteFileFromServer.js
server/middlewares/uploadFileToServer.js
server/middlewares/uploadToGoogle.js

854 worksite images

---

client/src/Components/Pages/Admin/Organizations/OrganizationsColumns.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Profile/Profile.style.js
server/controllers/admin/editOrganization.js
server/database/dummyData/questions.js

Fixes bugs #851 #852 and #868 
For #851, you need to rebuild the questions in the database.

Bugfixes > 851 852 868

---

.vscode/launch.json
client/src/Components/Common/Navbar/Menu.js
client/src/Components/Common/PrivateRoute/index.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Profile/OverviewSection/Level0Promo.js
client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
client/src/Components/Pages/Profile/OverviewSection/index.js
client/src/Components/Pages/Profile/Reply.js
client/src/Components/Pages/Profile/ReviewNotAllowedButton.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/Profile/utils.js
client/src/helpers/index.js
server/controllers/profile.js
server/database/queries/reviews/index.js

849 access levels

---

client/src/Components/Common/Navbar/Navbar.style.js
client/src/Components/Common/Navbar/index.js
client/src/Components/Pages/Search/AddProfileSelection.js
client/src/Components/Pages/Static/FAQ.js
client/src/Components/Pages/UserProfile/UserReviews.js

Correct a typo (+ update text)

---

client/src/Components/Pages/Admin/Reviews/ReviewsColumns.js
client/src/Components/Pages/Admin/Reviews/index.js
client/src/Components/Pages/Admin/Users/AllUsers.js
client/src/Components/Pages/Admin/Users/UsersColumns.js
client/src/Components/Pages/Admin/index.js
client/src/constants/adminRoutes.js
server/controllers/admin/getReviews.js
server/database/queries/reviews/allReviews.js
server/database/queries/user/allUsers.js

Changes to columns in Admin portal

---

client/src/Components/Pages/Profile/Profile.style.js

fix sticky banner overlay

---

client/src/Components/Common/Navbar/Menu.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/UploadImage/index.js
client/src/Components/Pages/UserProfile/UserReviews.js
server/controllers/uploadVerificationImage.js
server/middlewares/validation.js

Simon prio4 backlog chunk2

---

client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/utils.js
server/controllers/addCommentOnReview.js
server/database/queries/reviews/index.js

Relates to #857
Stops users from being able to reply to a comment if the admin has replied to that specific comment

857 > Prevent Replies if Admin Has Replied

---

client/src/Components/Common/GeneralTabs.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Search/Header/Tabs.js
client/src/Components/Pages/Search/Header/index.js
client/src/Components/Pages/Search/index.js

 fix reloading search page

---

client/package-lock.json
client/package.json
client/src/Components/Common/Select.js
client/src/Components/Pages/EditProfile/EditProfileSection.js
client/src/Components/Pages/Review/Question/Options/DropDown.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/UploadImage/index.js

show prompt when modals are opened

---

client/src/Components/Common/Navbar/Navbar.style.js
client/src/Components/Pages/Review/Question/Options/DateRange.js
client/src/Components/Pages/Review/Question/Options/Number.js
client/src/Components/Pages/Review/Question/Question.style.js

style changes

---

client/src/Components/Pages/Review/validationSchema.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/UploadImage/index.js
server/database/dummyData/questions.js

Show hidden question + delete text

---

server/router/index.js

fix edit reviews access level

---

client/src/Components/Common/Navbar/Menu.js
client/src/Components/Common/Navbar/index.js
client/src/Components/Common/PrivateRoute/index.js
client/src/Components/Pages/UserProfile/index.js
client/src/Components/index.js

 access levels

---

client/src/Components/Pages/UploadImage/index.js

disable prompt when user is awaiting/verified

---

client/src/Components/Pages/PreReview/PreReview.style.js
client/src/Components/Pages/PreReview/index.js
server/controllers/review.js
server/router/index.js

this PR solves a bug that happens when you try to click on the "give review" button and open it in a new tab. we pass the data that needed for that page through the Link state, so the opening it in a new tab will make not pass the data and the page crashes.
fixed by fetching data from backend if they missed
Relates #887

PreReview bug

---

client/src/Components/Pages/Signup/index.js

disable orgs to be auto selected for non worker users

---

client/src/Components/Pages/Profile/OverviewSection/OverallReview.js

disable report content link for un-logged in users

---

client/src/Components/Common/Button.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Profile/OverviewSection/ContractorsList.js

hide the contractor list if there is no more one

---

client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/UploadImage/index.js
client/src/Components/Pages/UserProfile/index.js
server/controllers/uploadVerificationImage.js

fix redirection for not-worker after sign-up

---

client/src/Components/Common/Navbar/index.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Profile/ProfileAnswers/YesNoAnswer.js

Minor bug fixes

---

client/src/Components/Common/Navbar/index.js

Render the missing items in the menu

---

client/src/Components/Pages/Review/Question/Options/DropDown.js
client/src/helpers/index.js

sort organisations alphabetically

---

client/src/Components/Pages/Search/AutoSuggest.js

update suggestion link

---

client/src/Components/Pages/Search/OrganisationRow.js

checks if storeOrg is instanceof Function

---

client/src/Components/Pages/Profile/OverviewSection/OverallReview.js

changed reviews by workers count to be written or audio reviews

---

client/package-lock.json
client/package.json
client/src/Components/Common/ReactSelect.js
client/src/Components/Common/Select.js
client/src/Components/Common/withSelect.js
client/src/Components/Pages/Review/Question/Options/DropDown.js
client/src/Components/Pages/Review/index.js
client/src/Components/Pages/Search/OrganisationRow.js

create virtualized select component

---

client/src/Components/Common/Navbar/Menu.js
client/src/Components/Common/Navbar/index.js
client/src/Components/Pages/Intro/index.js
client/src/Components/Pages/Landing/index.js
client/src/Components/Pages/Login/index.js
client/src/Components/Pages/OrgCheck/index.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/UserProfile/UserReviews.js
client/src/Components/index.js
client/src/constants/naviagationUrls.js

931 make welcome page landing page

---

client/src/Components/Common/withSelect.js

Fix the select trade bug

---

client/src/Components/Common/AddOrganisationPages.style.js
client/src/Components/Common/Button.js
client/src/Components/Pages/PreReview/PreReview.style.js
client/src/Components/Pages/PreReview/index.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/UploadImage/UploadImage.style.js
client/src/Components/Pages/UploadImage/index.js
client/src/Components/Pages/VerificationRequired/index.js
client/src/theme.js

918 update level 2

---

client/package-lock.json
client/src/Components/Common/RepliesAndCommentsCollaps/index.js
client/src/Components/Common/ReportFlag.js
client/src/Components/Pages/Profile/DetailedSection/DetailedAnswers.js
client/src/Components/Pages/Profile/DetailedSection/ReviewSection.js
client/src/Components/Pages/Profile/DetailedSection/index.js
client/src/Components/Pages/Profile/OverviewSection/ActionButtonsWrapper.js
client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
client/src/Components/Pages/Profile/OverviewSection/OverallReviewsContent.js
client/src/Components/Pages/Profile/OverviewSection/index.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/ProfileAnswers/index.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/Reply/index.js
client/src/Components/Pages/UploadImage/index.js
package-lock.json
package.json
server/controllers/updateLastViewedOrg.js

Fixes bugs #980 #982 #979 #960 #986

C4 bugs joe

---

client/src/Components/Pages/Signup/index.js
package.json
server/middlewares/validation.js

Fix validation for non-workers on signup

---

client/src/Components/Pages/ThankYou/index.js

fix username typo

---

client/src/Components/Common/RepliesAndCommentsCollaps/index.js
client/src/Components/Common/UserInfo.js
client/src/Components/Pages/Profile/OverviewSection/Replies.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Reply/Reply.style.js
client/src/Components/Pages/ReportContent/index.js
server/helpers/emails/mailer.js

report and reply bugs

---

package.json
server/config/index.js

update building production DB script

update building production DB script

---

client/src/Components/Pages/Search/index.js

Fix A-Z sort for recent reviewed organisations

---

client/src/Components/Common/Popover/index.js
client/src/Components/Pages/Profile/DetailedSection/ReviewSection.js
client/src/Components/Pages/Profile/ProfileAnswers/CanteenItemAnswer.js
client/src/Components/Pages/Profile/ProfileAnswers/ProfileAnswers.style.js
client/src/Components/Pages/Profile/ProfileAnswers/SiteItemAnswer.js
client/src/Components/Pages/Profile/ProfileAnswers/index.js
client/src/Components/Pages/Search/OrganisationsList.js
client/src/Components/Pages/Search/Search.style.js
client/src/Components/Pages/Search/index.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/UploadImage/index.js
client/src/Components/Pages/UserProfile/UserPoints.style.js
client/src/helpers/index.js
package.json
server/database/dummyData/questions.js
server/database/queries/search.js

PLEASE REBUILD DATA2
fixes text alignment from #1057 
fixes #1061, #1058, #1063

Bugfixing profile rendering and last reviewed search

---

client/src/Components/Common/Popover/index.js
package.json
server/controllers/admin/getSingleReview.js
server/controllers/review.js
server/database/queries/reviews/getReviewDetails.js

1064 bug fix

---

client/src/Components/Common/Navbar/Menu.js
client/src/Components/Common/PrivateRoute/index.js
client/src/Components/Pages/Profile/OverviewSection/ActionButtonsWrapper.js
client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
client/src/Components/Pages/Profile/OverviewSection/OverallReviewsContent.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/Profile/utils.js
client/src/helpers/index.js
package.json
server/controllers/admin/deleteUser.js
server/controllers/profile.js
server/database/queries/reviews/getOverallReplies.js
server/database/queries/reviews/index.js
server/database/queries/search.js
server/database/queries/user/index.js
server/middlewares/authorization.js

Relates #1075 
in case of verification process should be added again, search for `COMMENTED_VERIFICATION_CHECK` and uncomment the code under it

Disable verfiication

---

client/src/Components/Common/Navbar/Menu.js
client/src/Components/Pages/EditProfile/index.js
client/src/Components/Pages/InviteWorkers/index.js
client/src/Components/Pages/Signup/index.js
client/src/Components/Pages/Static/FAQ.js
client/src/Components/Pages/UserProfile/UserProfile.style.js
client/src/Components/Pages/UserProfile/index.js
client/src/Components/Pages/VerificationRequired/index.js
client/src/Components/Pages/Welcome/Welcome.style.js
client/src/Components/Pages/Welcome/index.js
server/helpers/emails/templates/createAccountEmail.js
server/middlewares/validation.js

Relates #1078 #1076 #1077 #1072 #1074 #1073

Content updates

---

client/src/Components/Common/GeneralTabs.js
client/src/Components/Common/Icon/Detailed.js
client/src/Components/Common/Navbar/Menu.js
client/src/Components/Pages/Profile/HeaderSection.js
client/src/Components/Pages/Profile/OverviewSection/OverallReview.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/ReviewNotAllowedButton.js
client/src/Components/Pages/Profile/index.js
client/src/Components/Pages/Search/OrganisationRow.js
client/src/Components/Pages/Search/Search.style.js
client/src/Components/Pages/Search/index.js
server/controllers/signup.js
server/database/queries/search.js
server/helpers/emails/index.js
server/helpers/emails/mailer.js
server/helpers/emails/templates/newUserAdded.js

Relates to #1091 #1092 #1090 #1082

March changes

---

server/controllers/signup.js

Add points for sign up

---

client/src/Components/Common/Icon/ParkingCost.js
client/src/Components/Pages/Profile/DetailedSection/DetailedAnswers.js
client/src/Components/Pages/Profile/DetailedSection/ReviewSection.style.js
client/src/Components/Pages/Profile/OverviewSection/OrganisationDetails.js
client/src/Components/Pages/Profile/OverviewSection/Replies.js
client/src/Components/Pages/Profile/Profile.style.js
client/src/Components/Pages/Profile/ReviewNotAllowedButton.js
client/src/theme.js

- Fix the crashing trade issue on review comments
- Fix padding

Fix comment bug
